/*==============================================================*/
/* DBMS name:      ORACLE Version 11g                           */
/* Script generado el:        11/06/2025                        */
/*==============================================================*/

/*======================== ELIMINAR CONSTRAINTS EXISTENTES ========================*/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE UBICACION DROP CONSTRAINT FK_UBICACIO_RELATIONS_TIPOUBIC';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE UBICACION DROP CONSTRAINT FK_UBICACIO_RELATIONS_UBICACIO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE "USER" DROP CONSTRAINT FK_USER_RELATIONS_UBICACIO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

/*======================== CREACIÓN DE TABLAS ========================*/

CREATE TABLE TIPOUBICA (
   CODTIPOUBICA      VARCHAR2(3)   NOT NULL,
   DESCTIPOUBICA     VARCHAR2(20)  NOT NULL,
   CONSTRAINT PK_TIPOUBICA PRIMARY KEY (CODTIPOUBICA)
);

CREATE TABLE UBICACION (
   CODUBICA          VARCHAR2(4)   NOT NULL,
   UBI_CODUBICA      VARCHAR2(4),
   CODTIPOUBICA      VARCHAR2(3)   NOT NULL,
   NOMUBICA          VARCHAR2(30)  NOT NULL,
   UBICA_SUP         VARCHAR2(4),
   CONSTRAINT PK_UBICACION PRIMARY KEY (CODUBICA)
);

CREATE TABLE "USER" (
   CONSECUSER        VARCHAR2(5)   NOT NULL,
   CODUBICA          VARCHAR2(4)   NOT NULL,
   NOMBRE            VARCHAR2(25)  NOT NULL,
   APELLIDO          VARCHAR2(25)  NOT NULL,
   "USER"            VARCHAR2(6)   NOT NULL,
   FECHAREGISTRO     DATE          NOT NULL,
   EMAIL             VARCHAR2(50)  NOT NULL,
   CELULAR           VARCHAR2(16)  NOT NULL,
   CONSTRAINT PK_USER PRIMARY KEY (CONSECUSER)
);

/*======================== ÍNDICES OPCIONALES ========================*/
CREATE INDEX RELATIONSHIP_2_FK ON UBICACION (CODTIPOUBICA ASC);
CREATE INDEX RELATIONSHIP_3_FK ON UBICACION (UBICA_SUP ASC);
CREATE INDEX RELATIONSHIP_1_FK ON "USER" (CODUBICA ASC);

/*======================== CLAVES FORÁNEAS ========================*/
ALTER TABLE UBICACION
   ADD CONSTRAINT FK_UBICACIO_RELATIONS_TIPOUBIC
   FOREIGN KEY (CODTIPOUBICA)
   REFERENCES TIPOUBICA (CODTIPOUBICA);

ALTER TABLE UBICACION
   ADD CONSTRAINT FK_UBICACIO_RELATIONS_UBICACIO
   FOREIGN KEY (UBICA_SUP)
   REFERENCES UBICACION (CODUBICA);

ALTER TABLE "USER"
   ADD CONSTRAINT FK_USER_RELATIONS_UBICACIO
   FOREIGN KEY (CODUBICA)
   REFERENCES UBICACION (CODUBICA);

/*======================== INSERCIÓN DE DATOS ========================*/

/* Tabla: TIPOUBICA */
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('1', 'País');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('2', 'Departamento');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('3', 'Ciudad');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('4', 'Area');
INSERT INTO TIPOUBICA (CODTIPOUBICA, DESCTIPOUBICA) VALUES ('5', 'Provincia');

/* Tabla: UBICACION (Países) */
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('57', 'Colombia', '1', NULL);
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('1', 'E.U', '1', NULL);
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('34', 'España', '1', NULL);
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('54', 'Argentina', '1', NULL);

/* Tabla: UBICACION (Departamentos de Colombia) */
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('05', 'Antioquia', '2', '57');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('81', 'Arauca', '2', '57');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('11', 'Bogotá D.C.', '2', '57');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('15', 'Boyacá', '2', '57');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('25', 'Cundinamarca', '2', '57');

/* Tabla: UBICACION (Estados de E.U.) */
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('205', 'Alabama', '4', '1');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('907', 'Alaska', '4', '1');
INSERT INTO UBICACION (CODUBICA, NOMUBICA, CODTIPOUBICA, UBICA_SUP) VALUES ('209', 'California', '4', '1');
